-- Supabase schema for HireIQ Lite

-- ===============================
-- 1. Profiles table: user info & role
-- ===============================
create table profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text unique,
    role text check (role in ('recruiter', 'candidate')) not null,
    created_at timestamptz default now()
);

-- ===============================
-- 2. Jobs table
-- ===============================
create table jobs (
    id bigint generated by default as identity primary key,
    recruiter_id uuid references profiles(id) on delete cascade,
    title text not null,
    description text,
    location text,
    created_at timestamptz default now()
);

-- ===============================
-- 3. Applications table
-- ===============================
create table applications (
    id bigint generated by default as identity primary key,
    job_id bigint references jobs(id) on delete cascade,
    candidate_id uuid references profiles(id) on delete cascade,
    cover_letter text,
    created_at timestamptz default now()
);

-- ===============================
-- Enable Row Level Security (RLS)
-- ===============================
alter table profiles enable row level security;
alter table jobs enable row level security;
alter table applications enable row level security;

-- ===============================
-- Suggested Basic RLS Policy Templates
-- ===============================

-- ---- PROFILES: Only owner can access/update their profile ----
-- Replace 'uid()' with the authenticated user's ID
create policy "Profiles: Self can select" on profiles
  for select using (auth.uid() = id);
create policy "Profiles: Self can update" on profiles
  for update using (auth.uid() = id);
create policy "Profiles: Self can delete" on profiles
  for delete using (auth.uid() = id);
-- (Do not allow anyone except sign-up process to insert.)

-- ---- JOBS: Only recruiters can insert, and recruiters can CRUD their own jobs ----
create policy "Jobs: Only recruiters can insert" on jobs
  for insert with check (
    exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'recruiter')
    and recruiter_id = auth.uid()
  );
create policy "Jobs: Recruiter can update own jobs" on jobs
  for update using (recruiter_id = auth.uid());
create policy "Jobs: Recruiter can delete own jobs" on jobs
  for delete using (recruiter_id = auth.uid());
create policy "Jobs: All users can read jobs" on jobs
  for select using (true);

-- ---- APPLICATIONS: Only candidates can insert for themselves; can read their own and relevant recruiters can read applications to their jobs ----
create policy "Applications: Only candidates can insert" on applications
  for insert with check (
    exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'candidate')
    and candidate_id = auth.uid()
  );
create policy "Applications: Candidate can update/delete own applications" on applications
  for update using (candidate_id = auth.uid());
create policy "Applications: Candidate can delete own applications" on applications
  for delete using (candidate_id = auth.uid());
create policy "Applications: Candidate can view own" on applications
  for select using (candidate_id = auth.uid());
create policy "Applications: Recruiter can view applications to their jobs" on applications
  for select using (
    exists (
      select 1 from jobs j
      where j.id = applications.job_id
      and j.recruiter_id = auth.uid()
    )
  );

-- ===============================
-- Notes:
-- * Carefully test and customize these policies in your Supabase project.
-- * The schemas and policies above assume direct frontend integration and effective authentication using Supabase Auth.
-- * Additional fields (like status, extra application info, etc.) or fine-grained permission can be added as needed.

-- ===============================
-- Migration instructions:
-- You can run this script directly in Supabase SQL editor, or split into migrations if using CLI tooling.
-- After running, adjust or fine-tune RLS policies in the Supabase dashboard as needed.
>>>>>>> END OF SCHEMA
