-- ===============================================
-- SUPABASE SCHEMA: HIREIQ LITE
-- For import into Supabase SQL editor or use with migrations
--
-- Contains:
--   * profiles table (auth-linked user, role)
--   * jobs table (recruiter-linked)
--   * applications table (job, candidate-linked)
--   * Recommended Row Level Security (RLS) policies for minimal viable protections
-- ===============================================

-- ===============================
-- 1. PROFILES TABLE (User, Role)
-- ===============================
drop table if exists profiles cascade;
create table profiles (
    id uuid primary key references auth.users(id) on delete cascade, -- maps to Supabase Auth user
    email text unique,
    role text check (role in ('recruiter','candidate')) not null,
    created_at timestamptz default now()
);

-- =========================
-- 2. JOBS TABLE (Recruiter)
-- =========================
drop table if exists jobs cascade;
create table jobs (
    id bigint generated by default as identity primary key,
    recruiter_id uuid not null references profiles(id) on delete cascade,
    title text not null,
    description text,
    location text,
    created_at timestamptz default now()
);

-- ==============================
-- 3. APPLICATIONS TABLE (by user)
-- ==============================
drop table if exists applications cascade;
create table applications (
    id bigint generated by default as identity primary key,
    job_id bigint not null references jobs(id) on delete cascade,
    candidate_id uuid not null references profiles(id) on delete cascade,
    cover_letter text,
    created_at timestamptz default now()
);

-- ==================================
-- Enable Row Level Security (RLS)
-- ==================================
alter table profiles enable row level security;
alter table jobs enable row level security;
alter table applications enable row level security;

-- =======================================
-- RLS POLICY TEMPLATES: Edit/customize as needed
-- =======================================

-- ---
-- PROFILES TABLE POLICIES - Only owner can select/update/delete their profile
-- ---
create policy "Select own profile" on profiles
    for select using (auth.uid() = id);

create policy "Update own profile" on profiles
    for update using (auth.uid() = id);

create policy "Delete own profile" on profiles
    for delete using (auth.uid() = id);

-- Note: Typically, insert into 'profiles' happens via a sign-up trigger or manually,
-- so no public insert policy here.

-- ---
-- JOBS TABLE POLICIES
-- Only recruiters can insert their own job postings,
-- Only recruiter can update/delete their own jobs
-- Anyone can select jobs
-- ---
create policy "Recruiters can insert job postings" on jobs
    for insert with check (
        exists (
            select 1 from profiles p 
            where p.id = auth.uid() and p.role = 'recruiter'
        )
        and recruiter_id = auth.uid()
    );

create policy "Recruiters can update own jobs" on jobs
    for update using (recruiter_id = auth.uid());

create policy "Recruiters can delete own jobs" on jobs
    for delete using (recruiter_id = auth.uid());

create policy "All can view jobs" on jobs
    for select using (true);

-- ---
-- APPLICATIONS TABLE POLICIES
-- Only candidates can insert their own applications,
-- Candidates can update/delete/select own applications,
-- Recruiter who owns the job can view applications to their jobs
-- ---
create policy "Candidates insert applications" on applications
    for insert with check (
        exists (
            select 1 from profiles p 
            where p.id = auth.uid() and p.role = 'candidate'
        )
        and candidate_id = auth.uid()
    );

create policy "Candidates update own applications" on applications
    for update using (candidate_id = auth.uid());

create policy "Candidates delete own applications" on applications
    for delete using (candidate_id = auth.uid());

create policy "Candidates view own applications" on applications
    for select using (candidate_id = auth.uid());

create policy "Recruiters view applications to their jobs" on applications
    for select using (
        exists (
            select 1
            from jobs j
            where j.id = applications.job_id
            and j.recruiter_id = auth.uid()
        )
    );

-- =========================================
-- NOTES:
-- * Test and further tailor these RLS policies in Supabase dashboard as needed.
-- * Assumes direct frontend integration with Supabase Auth for user identification.
-- * Additional columns or fields (ex: application status) may be added.
-- * Indexes, triggers, or audit tables can be created as extensions.
--
-- HOW TO USE:
-- * Paste this SQL into Supabase SQL editor, or run as part of migrations.
-- * After applying, test end-to-end with your integration to confirm intended access!
-- =========================================
